### ISSUE TITLE
About "from box import Box"

### ISSUE THREAD

**Issue by fupiao1998** [iwbn/unsupsimflow#1]
Hello, thank you very much for your outstanding work. When running your code, I encountered the following statement "from box import Box". My system prompts me that the box package does not exist. But when I tried "pip install box", it also prompted that the package does not exist. So I want to ask you how this package is configured.
At the same time, can you provide a model with training. Looking forward to your reply, thank you!

**Comment by iwbn** [comment]
Hello. Try to install python-box (https://pypi.org/project/python-box/). You may need to install python yaml package too.

**Comment by MaoYuxin25** [comment]
Thank you for your prompt reply!
